<?php

/**
 * @file
 * Primary module hooks for Double Field module.
 */

/**
 * Implements hook_theme().
 */
function double_field_theme() {
  $templates = [
    'item',
    'definition_list',
    'accordion',
    'tabs',
  ];
  foreach ($templates as $template) {
    $items['double_field_' . $template] = ['render element' => 'elements'];
  }
  return $items;
}

/**
 * Prepares variables for double-field-item template.
 */
function template_preprocess_double_field_item(&$vars) {

  $elements = &$vars['elements'];

  $vars['style'] = $elements['#settings']['style'];
  $vars['settings'] = $elements['#settings'];
  if ($vars['style'] == 'inline') {
    $vars['attributes']['class'][] = 'container-inline';
  }

  foreach (['first', 'second'] as $subfield) {
    if ($elements['#item']->{$subfield}) {
      $vars['item'][$subfield] = $elements['#item']->{$subfield};
    }
  }

}

/**
 * Prepares variables for double-field-definition-list template.
 */
function template_preprocess_double_field_definition_list(&$vars) {
  double_field_prepare_items($vars);
}

/**
 * Prepares variables for double-field-accordion template.
 */
function template_preprocess_double_field_accordion(&$vars) {
  double_field_prepare_items($vars);
}

/**
 * Prepares variables for double-field-definition-tabs template.
 */
function template_preprocess_double_field_tabs(&$vars) {
  double_field_prepare_items($vars);
}

/**
 * Prepare items.
 */
function double_field_prepare_items(&$vars) {
  $elements = &$vars['elements'];

  foreach ($elements['#items'] as $delta => $item) {

    foreach (['first', 'second'] as $subfield) {
      if ($item->{$subfield}) {
        $vars['items'][$delta][$subfield] = $item->{$subfield};
      }
    }

  }

}
